"""add in messages nullable true

Revision ID: 000000000004_558e95d4c866
Revises: 000000000003_95306fba5ee3
Create Date: 2024-05-08 23:40:04.533250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000000000004_558e95d4c866'
down_revision = '000000000003_95306fba5ee3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
