"""change commands

Revision ID: 000000000005_cf1c87611618
Revises: 000000000004_558e95d4c866
Create Date: 2024-05-08 23:45:53.240686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000000000005_cf1c87611618'
down_revision = '000000000004_558e95d4c866'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
