"""Initial migration

Revision ID: 000000000002_8ab8836858b5
Revises: 001_bd2da2835215
Create Date: 2024-05-08 23:02:59.950262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000000000002_8ab8836858b5'
down_revision = '001_bd2da2835215'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
